- name: Lege Mountpunkt für Volume an
  file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
  loop: "{{ gluster_client }}"
  when: gluster_client is defined

- name: Mounte Volume
  mount:
    src: "{{ gluster_server | selectattr('volume', 'equalto', item.volume) | map(attribute='peers') | first | product([ '.' + freifunk.domain + ':' + item.volume ]) | map('join') | first }}"
    path: "{{ item.path }}"
    fstype: "glusterfs"
    opts: "x-systemd-automount,_netdev,defaults,backup-volfile-servers={{ (gluster_server | selectattr('volume', 'equalto', item.volume) | map(attribute='peers') | first | product([ '.' + freifunk.domain ]) | map('join'))[1:] | join (':') }}"
    state: present
  loop: "{{ gluster_client }}"
  when: gluster_client is defined
  notify:
  - reread systemd configs
  - restart remote-fs
