- name: check if service for Kea dhcpd exists
  command: "systemctl cat kea-dhcp4.service"
  register: kea_dhcp4_exists
  failed_when: not (kea_dhcp4_exists.rc == 0 or kea_dhcp4_exists.rc == 1)
  changed_when: false
  check_mode: false

- name: stop and disable Kea dhcpd
  systemd:
    name: kea-dhcp4.service
    state: stopped
    enabled: false
  when: kea_dhcp4_exists.rc == 0

- name: install requirements
  apt:
    pkg: rsync

- name: create persitent folder dhcpd data
  file:
    path: /var/lib/dhcp_persistent
    state: directory
    mode: "0755"
  notify:
    - restart isc-dhcp-server

- name: Ramdisk in fstab eintragen
  mount:
    name: /var/lib/dhcp
    src: tmpfs
    fstype: tmpfs
    opts: 'defaults,size=100M'
    state: mounted
  notify:
    - restart isc-dhcp-server

- name: create dir for tmpfs scripts
  file:
    path: /usr/src/dhcpd
    state: directory
    mode: "0755"

- name: tmpfs start script for dhcpd
  template:
    src: openramdisk.j2
    dest: /usr/src/dhcpd/openramdisk
    mode: "a+x"

- name: tmpfs stop script for dhcpd
  template:
    src: closeramdisk.j2
    dest: /usr/src/dhcpd/closeramdisk
    mode: "a+x"

- name: tmpfs systemd service for dhcpd
  template:
    src: dhcpd-tmpfs.service.j2
    dest: /etc/systemd/system/dhcpd-tmpfs.service
    mode: "0644"
  notify:
    - reread systemd configs

- name: enable dhcpd-tmpfs service
  service:
    name: dhcpd-tmpfs
    enabled: true
    state: started

- name: install isc-dhcp-server
  apt:
    pkg: isc-dhcp-server

- name: create dhcp defaults
  template:
    src: isc-dhcp-server.j2
    dest: /etc/default/isc-dhcp-server
    mode: "0644"
  notify:
    - restart isc-dhcp-server

- name: create dhcpd config
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: "0644"
  notify:
    - restart isc-dhcp-server

- name: create folder for isc-dhcp-server service override file
  file:
    path: /etc/systemd/system/isc-dhcp-server.service.d
    state: directory
    mode: "0755"

- name: override isc-dhcp-server service
  template:
    src: isc-dhcp-server.service.override.j2
    dest: /etc/systemd/system/isc-dhcp-server.service.d/ansible-managed.conf
    mode: "0644"
  notify:
    - reread systemd configs
