- name: Installiere OpenSSL
  apt:
    name: [ "openssl" ]

- name: Erzeuge Private Key
  openssl_privatekey:
    path: /etc/ssl/glusterfs.key
    size: 2048
  notify: restart glusterd

- name: Erzeuge Self-Signed-Zertifikat
  openssl_certificate:
    path: /etc/ssl/glusterfs.pem
    privatekey_path: /etc/ssl/glusterfs.key
    selfsigned_not_after: "+36500d"
    provider: selfsigned
  notify: restart glusterd

- name: Lese Self-Signed-Zertifikat
  slurp:
    src: /etc/ssl/glusterfs.pem
  register: certfile

- name: Speichere Self-Signed-Zertifikat als Fact
  set_fact:
    glusterfs_cert: "{{ certfile['content'] | b64decode }}"

- name: Speichere die Zertifikate aller Gluster-Peers
  copy:
    content: "{{ groups['gateways'] | map('extract',hostvars, ['glusterfs_cert']) | join }}"
    dest: /etc/ssl/glusterfs.ca
  notify: restart glusterd

- name: TLS für Management-Traffic einschalten
  file:
    path: /var/lib/glusterd/secure-access
    state: touch
  notify: restart glusterd
