# raslöschen, force, rebalance, replica-count

# Volume anlegen
- name: Lege GlusterFS-Volume an
  gluster_volume:
    state: present
    host: "{{ inventory_hostname }}.servers.{{ freifunk.domain }}"
    volume: "{{ item.name }}"
    bricks: "/mnt/glusterfs/{{ item.name }}.image/brick"
    replicas: "{{ groups['gateways'] | length }}"
    cluster: "{{ groups['gateways'] | product([ '.' + freifunk.domain ]) | map('join') }}"
    rebalance: no  # nur wenn anzahl replicas != anzahl bricks
    #remove_bricks: yes  # noch dev
    options:
      network.ping-timeout: "10"
      client.ssl: "on"
      server.ssl: "on"
  loop: "{{ gluster.volumes }}"
  run_once: true

# Ansible Bug? Nach gluster_volume sind hier die Hostvars hin! - aber nur wenn sie "glusterfs" heißt... :(
