---
- name: Install dependencies
  apt:
    pkg: ['python3', 'ethtool', 'lsb-release']
    state: present

- name: Clone mesh-announce repo
  git:
    repo: https://github.com/ffnord/mesh-announce.git
    dest: /opt/mesh-announce
    clone: true
    update: true
    force: true
  notify: restart respondd

- name: create configuration
  template:
    src: respondd.conf.j2
    dest: /opt/mesh-announce/respondd.conf
    mode: "0644"
  notify: restart respondd

- name: create systemd file
  template:
    src: respondd.service.j2
    dest: /etc/systemd/system/respondd.service
    mode: "0644"
  notify: systemctl reload

- name: enable respondd
  systemd:
    name: respondd
    enabled: true
    masked: false
  notify: systemctl reload
