---
- name: restart fastd per domain
  systemd:
    name: fastd@{{ item.key }}legacy.service
    state: restarted
  when: item.value.fastd_key is defined
  with_dict: "{{ domaenenliste }}"

- name: reread systemd configs
  systemd:
    daemon_reload: yes

