---
- name: restart networking
  service_facts:
  changed_when: true
  notify: restart services

- name: restart services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - networking
    - isc-dhcp-server
    - kea-dhcp4
    #- tunneldigger
  when: item in ansible_facts.services and ansible_facts.services[item].state == "running"
