- name: whisper-resize
  become: yes
  become_user: _graphite
  shell: /usr/bin/whisper-auto-resize --doit /var/lib/graphite/whisper/icinga2 /etc/carbon

- name: restart carbon-cache
  service:
    name: carbon-cache.service
    state: restarted

- name: reload icinga2
  service:
    name: icinga2
    state: reloaded

- name: reload apache2
  service:
    name: apache2
    state: reloaded

- name: restart apache2
  service:
    name: apache2.service
    state: restarted
